### ISSUE TITLE
Feature Request: Shop Price Adjustment

### ISSUE THREAD

**Issue by GFreak01** [wcolding/SWR_apworld#10]
I've been feeling like the game can turn a bit grindy when trying to get enough money to buy things in the shop.

Could we get some options to adjust the price of things?
As an example, the Ocarina of Time AP allows shop prices of "affordable", random within various limits, etc..

**Comment by wcolding** [comment]
Boy do I have good news for you! I actually already implemented it, and it is playable in a preview release.

[apworld](https://github.com/wcolding/SWR_apworld/releases/tag/v0.7.0-preview)

[Client](https://github.com/wcolding/SWR_AP_Client/releases/tag/v0.7.0-preview)

After some more testing and client side stuff I will put out a full release of 0.7.0 so stay tuned for that.
