### ISSUE TITLE
Feature Request: Reverse Race Checks

### ISSUE THREAD

**Issue by GFreak01** [wcolding/SWR_apworld#2]
I assume the difficult part would be marking what races have been checked.

**Comment by wcolding** [comment]
You'd be right about that; I'm already modifying how the save context is used so I could have actual flags for the regular race completions. The vanilla game does something very weird that wouldn't let me distinguish passing a course with 4th place vs not having passed it at all.

Additionally, I don't think doing the whole game twice would be super interesting. However, what I have thought about doing is adding randomized mirror courses as an option. So there could be some mix of mirrored and not every seed.

**Comment by GFreak01** [comment]
awesome idea!  I'm glad you're working on this.

if you need any assistant play testing feel free to let me know.  I really enjoy playing SWR!

**Comment by wcolding** [comment]
It's not in the works yet. Work on this will have to wait until after course unlock rando is finished. I'll post more info in the SWR channel in the main AP server when I have it!

**Comment by GFreak01** [comment]
Sorry for the confusion, I meant thank you for working on this whole AP integration of SWR.

**Comment by wcolding** [comment]
[Latest release](https://github.com/wcolding/SWR_apworld/releases/tag/v0.6.0) has mirrored tracks as an option. Be sure to grab the latest client as well!
